services:
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: proxy-manager
    restart: always
    ports:
      - "80:80" #Http
      - "81:81" #Administración de la API
      - "443:443" #Https
    volumes:
      - ./npm_data:/data
      - ./npm_letsencrypt:/etc/letsencrypt
    networks:
      - red-cba

  servidor-bd:
    image: mysql:5.7
    container_name: servidor-bd
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - uptime-kuma-data:/app/data
    networks:
      - red-cba

  backend:
    image: adrianaluciadaza/sample-api:v1
    container_name: backend
    restart: always
    ports:
      - "5050:5050"
    environment:
      DB_HOST: servidor-bd
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      servidor-bd:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5050/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - red-cba

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: mi-phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: servidor-bd
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      servidor-bd:
        condition: service_healthy
    networks:
      - red-cba

volumes:
  mysql-data:
  uptime-kuma-data:
    name: uptime-kuma-data 

networks:
  red-cba: