services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - red-cba

  servidor-bd:
    image: mysql:5.7
    container_name: servidor-bd
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - red-cba

  backend:
    image: adrianaluciadaza/sample-api:v1
    container_name: backend
    restart: always
    ports:
      - "5050:5050"
    environment:
      DB_HOST: servidor-bd
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      - servidor-bd
    networks:
      - red-cba

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: mi-phpmyadmin
    restart: always
    ports:
      - "5050.5050"
    environment:
      PMA_HOST: servidor-bd
    depends_on:
      - servidor-bd
    networks:
      - red-cba

volumes:
  mysql-data:

networks:
  red-cba: